before_script:
    - echo "Before"

build_game:
  script:
    - export WORKDIR=$PWD
    - cd GalaxyGame
    - qmake
    - make install INSTALL_ROOT=$WORKDIR/build
  tags:
    - qt

test_game:
  script:
    - echo "Test"
  tags:
    - qt