before_script:
    - cd GalaxyGame/

course_tests:
  script:
    - cd CourseTests/ && qmake -o Makefile && make -f Makefile qmake_all
    - cd Galaxy/ && ./galaxytest
  tags:
    - qt

student_tests:
  script:
    - cd StudentTests/ && qmake -o Makefile && make -f Makefile qmake_all
    - cd Statistics/ && ./statisticstest
  tags:
    - qt