before_script:
    - echo "Before"

build_game:
  script:
    - export WORKDIR=$PWD
    - cd GalaxyGame/
    - qmake
    - cd CourseTests/ && qmake -o Makefile && make -f Makefile qmake_all && cd ..
    - cd StudentTests/ && qmake -o Makefile && make -f Makefile qmake_all && cd ..
    - cd .. && pwd
  tags:
    - qt

test_game:
  script:
    - echo "Test"
  tags:
    - qt